### ISSUE TITLE
Password Requirements in the next line

### ISSUE THREAD

**Issue by TanmayKalra09** [maniyaom/Movie-Ticket-Booking#1]
The Password Requirements can be shown in the next line in bullets for better understating

![Screenshot 2024-10-01 173216](https://github.com/user-attachments/assets/2638d1df-3a98-40b4-a4ed-5713a85ce46f)

**Comment by TanmayKalra09** [comment]
can you please assign this task to me?

**Comment by c2gup** [comment]
![Screenshot (181)](https://github.com/user-attachments/assets/a7f69430-819f-46ae-9db6-7d72d476f1ea)

@TanmayKalra09

I hope you’re doing well! I’m interested in working on the issue. I am sharing an image with you; if you want  like it, please assign it to me, and I will make it better. It’s really simple.

Thanks!

Anupam Gupta

**Comment by maniyaom** [comment]
> can you please assign this task to me?

Don't use bullets. just list the requirements on new line.

**Comment by TanmayKalra09** [comment]
> > can you please assign this task to me?
> 
> Don't use bullets. just list the requirements on new line.

Sure, thanks for assigning me the issue

**Comment by maniyaom** [comment]
@TanmayKalra09 There is some extra space before the error message. Please resolve it and do the same for all the fields in that form.

**Comment by TanmayKalra09** [comment]
@maniyaom, the changes are done.
Please review them and suggest if anything more is required.

**Comment by maniyaom** [comment]
> @maniyaom, the changes are done. Please review them and suggest if anything more is required.

Done
