### ISSUE TITLE
[Feat]: Implement the chatbot on the website

### ISSUE THREAD

**Issue by rutikakengal** [maniyaom/Movie-Ticket-Booking#100]
This will go to the top of the website and add gssoc-ext,hactoberfest accepted and level to the issue @maniyaom

**Comment by maniyaom** [comment]
@rutikakengal To justify adding the GSSoC-EXT label to your work, you'll need to incorporate additional features or functionality. Only then can I assign the label.

**Comment by rutikakengal** [comment]
i'll add chatbot to the website

**Comment by rutikakengal** [comment]
@maniyaom

**Comment by maniyaom** [comment]
@rutikakengal Okay, create one button in contact us page by which user can access that chatbot.

**Comment by maniyaom** [comment]
@rutikakengal no update? Closing this issue if you don't respond to this.
