### ISSUE TITLE
login button hover

### ISSUE THREAD

**Issue by Monu2114** [maniyaom/Movie-Ticket-Booking#101]
Hover functionality in login button

**Comment by maniyaom** [comment]
@Monu2114 To justify adding the GSSoC-EXT label to your work, you'll need to incorporate additional features or functionality. Only then can I assign the label.

**Comment by pameladeysarkar2003** [comment]
You can also change color to backgroundColor -- not sure which one you'd want for what you're doing.

I can include CSS code to achieve the same thing if you want, but it's not really necessary if you only want to do this for one button.
 @maniyaom kindly please assign me with this task

**Comment by maniyaom** [comment]
@pameladeysarkar2003 Don't spam in all the issues. If you find any issues in the website which is not available in issue section then raise it. If that will be valid issue I will assign it to you.
