### ISSUE TITLE
Improve UI for about us page and contact us page with overall responsiveness and animation

### ISSUE THREAD

**Issue by Om-Thanage** [maniyaom/Movie-Ticket-Booking#102]
![image](https://github.com/user-attachments/assets/232579c5-59e6-408e-acd4-72b7f6f287cd)

I would like to improve the UI with some animations and responsiveness 

Pls can you assignee me this issue @maniyaom

**Comment by maniyaom** [comment]
@Om-Thanage This is not an issue with the contact us page. It became unresponsive due to the navbar.
