### ISSUE TITLE
Add Newsletter Feature to Project

### ISSUE THREAD

**Issue by wajaht-ali** [maniyaom/Movie-Ticket-Booking#106]
**Description**: 
A newsletter feature is essential for keeping subscribers informed about weekly or monthly updates. This feature will help improve the relationship between the project owner and users by keeping them engaged and up-to-date with the latest developments, news, and special offers.

**Proposed Solution**:
 I will implement the newsletter feature on the front end using ReactJS, along with appropriate styling to ensure a seamless user experience. This feature will allow users to easily subscribe to the newsletter and receive updates. Please assign me this issue so I can start working on it.

**Comment by maniyaom** [comment]
@wajaht-ali the homepage is currently in progress. Once it's complete, you can start working on it.

**Comment by maniyaom** [comment]
@wajaht-ali Please remind me tomorrow or the day after tomorrow if I forget to inform you.

**Comment by wajaht-ali** [comment]
@maniyaom Sure, I'll let you know.

**Comment by maniyaom** [comment]
@wajaht-ali just wait for tomorrow.

**Comment by maniyaom** [comment]
@wajaht-ali can you start working on it?

**Comment by wajaht-ali** [comment]
Sure! But can you please provide me the **guest login** credentials or any suitable way to navigate and get access easily? I'm facing issues while creating passwords due to strong validations.
My email: "contact.chwajahat@gmail.com"

**Comment by maniyaom** [comment]
@wajaht-ali You can create your own account. Just follow the password policy.
It should contain 1 Capital letter, 1 Small letter, 1 number and 1 special character also password length should be more than 8 characters.

**Comment by wajaht-ali** [comment]
@maniyaom I forked the repository but my development environment refused to accept the Firebase credentials you're using moreover there is also a problem with CORS, a cross-origin request which is by default not allowed according to the policy. 
If the integrity can't be compromised, then we may consider closing this issue. As you want.
