### ISSUE TITLE
Home Page Mobile View Responsiveness

### ISSUE THREAD

**Issue by Hrishikesh-Dalal** [maniyaom/Movie-Ticket-Booking#109]
**Hello Om!**

I would like to make changes to the home page as the responsiveness for the mobile view is not up to the mark. The content of the page in the mobile view should be center aligned, which it currently isn't. I would like to address that.

=
![Screenshot 2024-10-04 165014](https://github.com/user-attachments/assets/23031e77-70be-4372-86e5-3403efef395c)

As shown in this image.

**The changes:**

- The content of the home page should be center aligned and beautified.
- The image size should be reduced in the mobile view for the same

Additionally, I am part of GSSOC Extended. I would like to add the labels for Hacktoberfest and GSSOC Extended.

**Comment by krish2366** [comment]
@maniyaom , we have to only fix navbar here. Content is presenting perfectly. If you could assign me this task i'll do it easily.

**Comment by maniyaom** [comment]
@Hrishikesh-Dalal , krish2366 is right. This issue is due to navbar homepage is responsive.
