### ISSUE TITLE
[Feature Enhancement] : ✨Dark mode toggle✨ 

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [maniyaom/Movie-Ticket-Booking#110]
I have noticed a task has been assigned on it 2 days before and since there isnt any action on it , can you assign me the task? I'll work on it asap.
Thank you!

**Comment by maniyaom** [comment]
@T-Rahul-prabhu-38 I'll need to check with him first. Please avoid creating duplicate issues. If he’s unable to resolve the original issue, I’ll assign it to you directly.

**Comment by T-Rahul-prabhu-38** [comment]
sure!   looking forward to it.
