### ISSUE TITLE
Add Automated Greeting Workflow

### ISSUE THREAD

**Issue by harish08102004** [maniyaom/Movie-Ticket-Booking#111]
I propose to create a Github workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greetings will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open - source project. We aim to respond or assign your issue as soon as possible.

Hey @maniyaom I can work on this.

**Comment by maniyaom** [comment]
@harish08102004 any update?

**Comment by harish08102004** [comment]
Will close it today.

**Comment by maniyaom** [comment]
for Issue use this message: 

Thank you for raising this issue!

We appreciate your contribution to this project and will review the details shortly. We will get back to you soon.

Thank you for your patience!

for PR use this message:

Thank you for your Pull Request!

We appreciate your contribution. We will review the changes and provide feedback or merge the PR soon. Please stay tuned for updates.

Thank you for your efforts in improving the project!
