### ISSUE TITLE
[Feat]: Improve the UI of the My Tickets Page

### ISSUE THREAD

**Issue by iAmDiksha** [maniyaom/Movie-Ticket-Booking#112]
### Feature Description

The UI of the My Tickets Page is needed to be improved.

### Provide a detailed description of the feature

The current UI of the "My Tickets" page requires an update to enhance user experience and make it more visually appealing. The page should be designed with a modern look while maintaining responsiveness across all devices.

### Put here any screenshots or videos (optional)

<img width="958" alt="image" src="https://github.com/user-attachments/assets/33ea640b-a138-41b0-9e26-c4d8a82ac595">

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by maniyaom** [comment]
@iAmDiksha View ticket page is responsive but if you have any better design idea please share it here.

**Comment by iAmDiksha** [comment]
@maniyaom 

The page is responsive, but the UI is quite basic. On the desktop version, there's too much horizontal space on the right side. There should be at least two cards per row on the desktop, with box shadows on the cards and a hover effect for better interactivity.

**Comment by maniyaom** [comment]
@iAmDiksha simply adjusting the horizontal spacing and adding two cards in a row won't justify your work for the 'gssoc-ext' and 'hacktoberfest-accepted' labels. However, if you can enhance the design further, it may justify your contribution. Let me know if you have any other ideas.

**Comment by iAmDiksha** [comment]
> 
 @maniyaom 

Adding images of the movie on the tickets, which are currently not there.
