### ISSUE TITLE
[Feat]: Password strength check can be added in signup page

### ISSUE THREAD

**Issue by jvkousthub** [maniyaom/Movie-Ticket-Booking#114]
### Feature Description

In the signup page password strength indicator can be added that shows the strength based on the characters being used in the password

### Provide a detailed description of the feature

Implement a Password Strength Indicator in the signup page to help users create strong and secure passwords. The password strength indicator will provide real-time feedback on the strength of the password being entered, based on various criteria. This will improve user experience and promote better security practices by encouraging stronger passwords.

Password Strength Evaluation: The strength of the password will be evaluated as the user types, and feedback will be provided in real-time. The evaluation will be based on the following criteria:

Length: Minimum password length (e.g., 8 characters or more).
Character Variety: Use of a combination of different types of characters such as:
Uppercase letters (A-Z)
Lowercase letters (a-z)
Digits (0-9)
Special characters (e.g., !@#$%^&*)
Repetition: Avoidance of consecutive or repetitive characters.
Common Passwords: Warning if a password is commonly used or easily guessable.
Strength Levels: The password strength indicator will classify the password into the following levels:

Very Weak: Password has only lowercase letters or is too short.
Weak: Password includes uppercase or numbers but is still too short or not complex enough.
Moderate: Password meets length and variety requirements but could be stronger.
Strong: Password is long and contains a mix of uppercase, lowercase, numbers, and special characters.
Very Strong: Password meets all security requirements, including length, variety, and complexity.
Visual Feedback: The password strength indicator will provide visual feedback through:

Color-coded progress bar: As the password is typed, a progress bar will fill up and change color:
Red for "Very Weak"
Orange for "Weak"
Yellow for "Moderate"
Light green for "Strong"
Dark green for "Very Strong"
Text labels: Corresponding to the current strength level, e.g., "Very Weak", "Strong", etc.
Guidance: Short prompts or tooltips suggesting how to improve the password, e.g., "Add a special character", "Use a mix of uppercase and lowercase", etc.
Password Matching: If there is a Confirm Password field on the form, an additional check will be added to ensure that both the original and confirmed passwords match. If not, a warning will be displayed.

Implementation Notes:

Frontend Technologies: The password strength indicator can be implemented using JavaScript, CSS, and possibly a password-strength validation 

Responsiveness: The feature should be responsive and work well on mobile devices as well as desktop views.

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by jvkousthub** [comment]
@maniyaom assign me with this feature enhancement

**Comment by maniyaom** [comment]
@jvkousthub have you gone through the website? It is already implemented.
