### ISSUE TITLE
[Feat]: Add FAQs to the home page

### ISSUE THREAD

**Issue by anshika-1102** [maniyaom/Movie-Ticket-Booking#127]
### Feature Description

Frequently Asked Questions

### Provide a detailed description of the feature

It will help users to get their queries answered.

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by maniyaom** [comment]
@anshika-1102 It is duplicate issue.
Refer: Issue 61
