### ISSUE TITLE
Adding new and attractive images

### ISSUE THREAD

**Issue by rakshit-upadhyay214** [maniyaom/Movie-Ticket-Booking#13]
![image](https://github.com/user-attachments/assets/8d54b1e7-5bf3-4a41-b8bb-38f336059c76)
Don't these seem like dull pictures?

**Comment by maniyaom** [comment]
@rakshit-upadhyay214 , Thank you for creating the issue, but I don't think the pictures are dull. If you find any other issues, please let me know.
