### ISSUE TITLE
[Feat]: Migration to tailwind CSS - Home Page

### ISSUE THREAD

**Issue by maniyaom** [maniyaom/Movie-Ticket-Booking#131]
### Feature Description

Use Tailwind CSS in Home page

### Provide a detailed description of the feature

1. Responsive Design
2. Dark Mode Support

### Put here any screenshots or videos (optional)

![image](https://github.com/user-attachments/assets/89e9a20c-14c0-4f64-9f73-f0a3635a59dc)

### By submitting this issue, you agree to

- [x] I agree to follow this project's Code of Conduct
- [x] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [x] I'm a GSSoC '24 Extended contributor
- [x] I'm a Hacktoberfest '24 contributor
- [x] I am willing to work on this feature (optional)

**Comment by AayushiJapsare15** [comment]
hello @maniyaom 
I would love to work on this issue please assign it to me.

I have used tailwind on multiple projects before, i have the experience to satisfy your need.

**Comment by maniyaom** [comment]
@AayushiJapsare15 I have configured Tailwind CSS in the project. Please start working on it and make sure the design is responsive on all devices.

**Comment by biswajit-sarkar-007** [comment]
Hi, I'm interested in solving this. Can I be assigned?

**Comment by maniyaom** [comment]
@biswajit-sarkar-007 It is already assigned.

**Comment by AayushiJapsare15** [comment]
I have started working on it. 
Would like you to please add 'hacktoberfest-accepted' label as well since it is crucial for hacktober and level label.

**Comment by AayushiJapsare15** [comment]
I have started working on it. Until then can you please add level label as well

**Comment by maniyaom** [comment]
@AayushiJapsare15 I will review your code based on that I will assign you level.

**Comment by DeshDeepakKushwaha** [comment]
i want to work on this,If no one is working currently then can u please assign this issue to me

**Comment by maniyaom** [comment]
@AayushiJapsare15 Is there any progress?

**Comment by AayushiJapsare15** [comment]
yes @maniyaom I have emailed you

**Comment by maniyaom** [comment]
@AayushiJapsare15 please share the information in the relevant issue thread instead of sending a separate email. This will make it easier to maintain everything in one place.

You have implemented it for only two pages?

**Comment by AayushiJapsare15** [comment]
yes for home page and movie details page

**Comment by maniyaom** [comment]
Okay, Raise the PR.

**Comment by code-withGV** [comment]
ello @maniyaom
I would love to work on this issue please assign it to me.
Here I can make this simple looking webpage more attractive and impressive.
I have a good command on Tailwind and used it on multiple projects before, i have the experience to satisfy your need.
