### ISSUE TITLE
[Feat]: Dynamic QR of Movie Ticket

### ISSUE THREAD

**Issue by Akshithsaai** [maniyaom/Movie-Ticket-Booking#133]
### Feature Description

Dynamic QR of Movie Ticket Details

### Provide a detailed description of the feature

The Current QR Code in Movie Ticket is being redirected to a youtube video. We can change this to a QR generated at the frontend with the accurate ticket details. Instead of a Fake QR, I suggest displaying the QR code with valid ticket details. 

I would like your suggestions and improvements on this feature @maniyaom . 

### Current View of QR Code: 
![image](https://github.com/user-attachments/assets/1e54b94b-9396-4617-8c63-5d99ee9417d8)

### Relevant QR code: 
![image](https://github.com/user-attachments/assets/2bb0fe47-274c-41e0-8d0c-65e07d248187)

![image](https://github.com/user-attachments/assets/340724fa-cc79-4cd8-bf1e-c99fb9d4a412)

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by maniyaom** [comment]
@Akshithsaai can we make a QR code that can be scanned once and then it becomes invalid.

**Comment by Akshithsaai** [comment]
@maniyaom definitely, I will work on that feature. If there are any other suggestions please let me know.

**Comment by maniyaom** [comment]
@Akshithsaai Okay, Start working on it.

**Comment by Akshithsaai** [comment]
@maniyaom For implementing this feature I need to use backend files. How can i access the backend?

**Comment by maniyaom** [comment]
This code is only made of React Js and Firebase.

**Comment by Akshithsaai** [comment]
### Shown using QR Scanner
Here I have used the scanner to show the proper working of the Scanner.

https://github.com/user-attachments/assets/44109952-f6a6-4740-98ef-af74353c5737

###  Using Files from Computer 
Here I have Booked a ticket and Taken the screenshot of the qr which and verified it. As you can see, once  for the second time the QR is not valid.

https://github.com/user-attachments/assets/b82cfea9-febb-422e-8760-48de9c7d6885

please check it out @maniyaom

**Comment by Akshithsaai** [comment]
@maniyaom Shall I proceed to PR ?

**Comment by maniyaom** [comment]
@Akshithsaai go ahed. I hope it is responsive for mobile also.

**Comment by Akshithsaai** [comment]
Ok @maniyaom I will raise a PR. Before that I will ensure about responsiveness in mobile.
