### ISSUE TITLE
Make the About us and contact us  page  responsive

### ISSUE THREAD

**Issue by AyushSharma72** [maniyaom/Movie-Ticket-Booking#14]
the contact us page and about us page are not responsive can make them responsive 

![image](https://github.com/user-attachments/assets/2a046fd7-15a8-4209-a699-c85085e95f7f)

can u assign this task to me @maniyaom

**Comment by maniyaom** [comment]
@AyushSharma72 Currently another contributor is working on Contact Us page, but you can enhance About Us page.

**Comment by AyushSharma72** [comment]
Okay thank you I will reach out to you soon
