### ISSUE TITLE
[Feat]: UI enhancement 

### ISSUE THREAD

**Issue by Soumya03007** [maniyaom/Movie-Ticket-Booking#140]
### Feature Description

UI enhancement

### Provide a detailed description of the feature

I want to add some more CSS stylings to look this website amazing 

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by maniyaom** [comment]
@Soumya03007 don't give general statements. Specify the page name or the function you want to implement.

**Comment by Soumya03007** [comment]
I want to add some css stylings in the nav bar , in the body part and some parallax effect and also some 3d effects

**Comment by pameladeysarkar2003** [comment]
@maniyaom kindly please assign me with this task.
by adding necessary padding and css effects in the body ,header,footer will make it more interactive and user friendly

Also add hactoberfest and gssoc extd

**Comment by maniyaom** [comment]
@Soumya03007 could you please ensure that the issues raised are aligned with the core functionality of the website? We encourage contributions that help enhance its primary features.
