### ISSUE TITLE
Add Hover Effect to Navbar Items

### ISSUE THREAD

**Issue by Abhishek-TG18** [maniyaom/Movie-Ticket-Booking#149]
### Feature Description

Add Hover Effect to Navbar Items

### Provide a detailed description of the feature

This feature aims to enhance the user experience by adding a hover effect to the navbar items on the homepage. When users hover over the navigation links, a visual feedback will be provided to indicate that the items are interactive. This can include effects such as changing the background color, text color, or adding an underline to the links.

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by DeshDeepakKushwaha** [comment]
hello there!I want to work on this project .It would be my pleasure if you assigne me!

**Comment by maniyaom** [comment]
@Abhishek-TG18 @DeshDeepakKushwaha To justify adding the "gssoc-ext" label to your work, you'll need to incorporate additional features or functionality. Only then can I assign the label.

**Comment by DeshDeepakKushwaha** [comment]
I am also participating in hacktober fest  so I need the label for that
too!.
What else functionality or feature do I need to implement?

**Comment by Abhishek-TG18** [comment]
Ok
