### ISSUE TITLE
Better UI for Easier Listing of Movies

### ISSUE THREAD

**Issue by Akshithsaai** [maniyaom/Movie-Ticket-Booking#15]
### **Issue :**
The current form layout displays all form fields in a single column. To improve the layout and user experience, we need to display the input fields effectively. Each column should contain specific form elements, ensuring that the layout remains responsive and visually balanced.

#### Current UI:
![image](https://github.com/user-attachments/assets/161bd3f5-4a49-4019-8e0c-da5cc95bf563)

#### Expected UI:
![image](https://github.com/user-attachments/assets/4a4f83a7-6ec1-456f-8321-a33dbbc3aed0)

### **Checklist**
- [x] I have checked the existing issues
- [x]  I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [x] I'm a GSSoC'24-Extd contributor
- [x] I'm a Hacktoberfest'24 contributor
- [x] I am willing to work on this issue (optional)

I am ready to create a pull request if assigned! Please assign me this issue @maniyaom

**Comment by maniyaom** [comment]
@Akshithsaai , make these changes, but ensure that it will be responsive.
