### ISSUE TITLE
Contribution.md

### ISSUE THREAD

**Issue by Rx-Metallica** [maniyaom/Movie-Ticket-Booking#16]
Add code of conduct and contribution guidelines

**Comment by Rx-Metallica** [comment]
> Add code of conduct and contribution guidelines

Please assign this to me i will like to work on it

**Comment by adityakalburgi** [comment]
> @Rx-Metallica Could you please create a contributing.md file with all the required instructions? It's an urgent.

@maniyaom HI i can do that if you assign it to me!!
