### ISSUE TITLE
Missing footer section and Social media Icon

### ISSUE THREAD

**Issue by Vaibhavkumar5158** [maniyaom/Movie-Ticket-Booking#161]
Clickable social media icons can be added to the footer of the website .

for eg. like this image .
![image](https://github.com/user-attachments/assets/f5d1e058-cad5-4739-8568-c8dd76226ecc)

I would like to work on this issue .

Pls add GSSOC EXTD'24 and HACKTOBERFEST Badge and approriate level.
 @maniyaom 

Thank you, looking forward to contribute .

**Comment by ishanguptaofficial** [comment]
Hello maniyaom Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
