### ISSUE TITLE
DOC: Add CONTRIBUTING.md File

### ISSUE THREAD

**Issue by HarshadaGirase** [maniyaom/Movie-Ticket-Booking#173]
Description :
A contributing guide helps developers understand how they can contribute to the project, providing guidelines for submitting issues, creating pull requests, and general contribution practices. This will improve the overall contribution process and ensure that the codebase remains organized and consistent.

Benefits:

Helps new contributors understand the contribution workflow.
Encourages more organized and consistent contributions.
Reduces the amount of back-and-forth communication during code reviews and issue submissions

**Comment by HarshadaGirase** [comment]
@maniyaom  I would like to work on this issue kindly assign it to me ASAP.

**Comment by maniyaom** [comment]
@HarshadaGirase It is already there, checkout [CODE_OF_CONDUCT.md](https://github.com/maniyaom/Movie-Ticket-Booking/blob/master/CODE_OF_CONDUCT.md)
