### ISSUE TITLE
[Bug]: Home page is not much attractive and the page is not redirecting.

### ISSUE THREAD

**Issue by akansha-02** [maniyaom/Movie-Ticket-Booking#177]
### Bug Description

Home page is not much attractive and the page is not redirecting.

### Provide a detailed description of the bug

Images related to movies can be added to make the page more alluring and a logo can be added to enhance the page.
A directory link can be added to redirect the home page.

### Expected Behavior

Will be adding images on the home page making it look more attractive.
A link for re directing the home page.

Please assign me these issues under Hacktoberfest and gssoc'24 extended.

### What browsers are you seeing the problem on?

Chrome

### Put here any screenshots or videos (optional)

![image](https://github.com/user-attachments/assets/81b391b2-19ad-424f-882b-8a121ad45569)

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this has not been reported yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by akansha-02** [comment]
Please assign me these issues under Hacktoberfest and gssoc'24 extended.

**Comment by Syed-Shamsheer-Ali** [comment]
Please assign it to me.I want to work on it

**Comment by maniyaom** [comment]
@akansha-02 This is not the issue. You have to first login to access home page.

**Comment by Khizarshah01** [comment]
duplicate
