### ISSUE TITLE
[Backend]: Debouncing effect is not there in searching feature.

### ISSUE THREAD

**Issue by aryadevesh** [maniyaom/Movie-Ticket-Booking#183]
### Feature Description

Optimised utilization of search query in the backend, saving queries usage cost.

### Provide a detailed description of the feature

The search function in your code does not currently implement a debouncing effect. Debouncing is used to limit the rate at which a function is executed. In the context of searching, it prevents the search function from being called on every keystroke, instead delaying the execution until the user has stopped typing for a certain period.

### Put here any screenshots or videos (optional)

<img width="770" alt="image" src="https://github.com/user-attachments/assets/689f2ef5-9c23-4dd6-bf8f-01731b74ec50">

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by maniyaom** [comment]
@aryadevesh Assigned.
