### ISSUE TITLE
[Important]: The password validation is not there in the backend 

### ISSUE THREAD

**Issue by aryadevesh** [maniyaom/Movie-Ticket-Booking#184]
### Feature Description

Missing strong password validation in the backend 

### Provide a detailed description of the feature

# Missing Advanced Password Validation
- There are no checks for password strength, length, or complexity. For instance:
- No validation for minimum length (e.g., 8 characters).
- No validation for the presence of uppercase, lowercase, numbers, or special characters.
- No validation for common password vulnerabilities (e.g., checking if the password is weak).

### Put here any screenshots or videos (optional)

<img width="430" alt="image" src="https://github.com/user-attachments/assets/2c857ac6-103d-4b90-8009-83d9aa4b81b1">

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by maniyaom** [comment]
Go through the website before raising any issue. This is already implemented.
