### ISSUE TITLE
add Contributing.md file

### ISSUE THREAD

**Issue by Amulya-B28** [maniyaom/Movie-Ticket-Booking#193]
I would like to add this file because it is a crucial document in open-source repositories, providing clear guidelines and instructions for anyone interested in contributing to the project. It outlines how contributors can get involved, the contribution process, and the repository's coding standards and rules. Please assign this task to me.

**Comment by maniyaom** [comment]
@Amulya-B28 It is already there, checkout [CODE_OF_CONDUCT.md](https://github.com/maniyaom/Movie-Ticket-Booking/blob/master/CODE_OF_CONDUCT.md)
