### ISSUE TITLE
Make Login Page Responsive and Look Better

### ISSUE THREAD

**Issue by Rx-Metallica** [maniyaom/Movie-Ticket-Booking#196]

**Comment by Rx-Metallica** [comment]
> 

Pls assign me

**Comment by maniyaom** [comment]
@Rx-Metallica another contributor is currently working on fixing the Sign Up and Login page. I encourage you to explore and contribute to other issues on the website.

**Comment by Rx-Metallica** [comment]
> @Rx-Metallica another contributor is currently working on fixing the Sign Up and Login page. I encourage you to explore and contribute to other issues on the website.

Can we make changes in login page untill he fix the issue cause i have made changes in login page and in styles and it is  better for readability.

**Comment by maniyaom** [comment]
@Rx-Metallica He is working on the Login and Sign-Up page UI to improve overall responsiveness and convert it to Tailwind CSS.
