### ISSUE TITLE
Home page and design

### ISSUE THREAD

**Issue by Mahy-31** [maniyaom/Movie-Ticket-Booking#2]
Home page and login page traverse to the same login page. It will look better if the home page is made to an attractive landing page with some pics and details. In addition to that, I believe the contact page can be redesigned and developed. Could you please assign this task to me?

**Comment by maniyaom** [comment]
> Home page and login page traverse to the same login page. It will look better if the home page is made to an attractive landing page with some pics and details. In addition to that, I believe the contact page can be redesigned and developed. Could you please assign this task to me?

Actually, when user is not logged in to the website. It will redirect them to login page. Yes, you can enhance or redesign Contact Us page.

**Comment by Mahy-31** [comment]
> > Home page and login page traverse to the same login page. It will look better if the home page is made to an attractive landing page with some pics and details. In addition to that, I believe the contact page can be redesigned and developed. Could you please assign this task to me?
> 
> Actually, when user is not logged in to the website. It will redirect them to login page. Yes, you can enhance or redesign Contact Us page.

Thank you for assigning me this task. Will reach out to you soon, after completing it.

**Comment by maniyaom** [comment]
@Mahy-31 any update?

**Comment by Mahy-31** [comment]
> @Mahy-31 any update?

Working on it sir. Will get back to you shortly

**Comment by Mahy-31** [comment]
Also can you label this issue as hacktibetfest-accepted please?

**Comment by maniyaom** [comment]
@Mahy-31 What's the update? will assign level after reviewing your code.

**Comment by Mahy-31** [comment]
An issue has occurred and i'm unable to pull request. I will resolve all the issues and get back to you. Sorry for the inconvinience.

**Comment by maniyaom** [comment]
@Mahy-31 There is no update since a week.

**Comment by Mahy-31** [comment]
> @Mahy-31 There is no update since a week.

I have created a PR. Kindly check that.
