### ISSUE TITLE
make the logos attractive

### ISSUE THREAD

**Issue by Risheendra183** [maniyaom/Movie-Ticket-Booking#20]
in the about us and contact us,footer section the logos are not that attractive i can solve .please assign me this and add label gssoc'24 ext and level
![image](https://github.com/user-attachments/assets/8b20b55b-a8f7-4e85-b86b-7ef1ded9c2c4)

**Comment by Risheendra183** [comment]
![image](https://github.com/user-attachments/assets/15f6ff9e-9009-4fc7-93c0-3341395648a5)

**Comment by maniyaom** [comment]
@Risheendra183 Thank You for raising issue, but there is no need of improvement in that if you find any other issues raise another issue.
