### ISSUE TITLE
Proposal: Convert Frontend from Vanilla CSS to Tailwind CSS for Improved Efficiency and Responsiveness

### ISSUE THREAD

**Issue by anuragbansall** [maniyaom/Movie-Ticket-Booking#208]
Hey, @maniyaom I noticed the frontend is currently built using React.js and vanilla CSS. I believe it would be beneficial to convert the vanilla CSS to Tailwind CSS, as it aligns better with React.js and will improve efficiency for frontend developers who work on this project in the future. If no one is currently assigned to this task, please consider assigning it to me.

Here’s what I plan to do:

- Revamp the entire structure using Tailwind CSS

- Fix any existing responsiveness issues

**Comment by maniyaom** [comment]
@anuragbansall Please be specific about page name. I have already assigned some pages for conversion from Venila CSS to Tailwind CSS.

**Comment by anuragbansall** [comment]
@maniyaom I’m planning to revamp all the pages, but since some people are already working on certain ones, could you let me know which pages are available? I’ll focus on revamping one of those.

**Comment by sanjogbhalla16** [comment]
Can I also work on this issue , its my first time and would love to work on this.

**Comment by maniyaom** [comment]
@anuragbansall for now, please convert the Login and Sign Up UI to Tailwind CSS. Ensure that the pages are responsive across all devices.

**Comment by sanjogbhalla16** [comment]
Hi @maniyaom, can I also work in this issue , I would love to share my inputs in this and it will be a great experience for me also as it is my first time in contributing.

**Comment by anuragbansall** [comment]
Hey @maniyaom ,

I’ve successfully converted the Login and Sign Up pages to Tailwind CSS, ensuring they’re fully responsive across all devices. I’ve raised a PR, please take a look and let me know if you have any suggestions or improvements!

Thanks!
