### ISSUE TITLE
[Feat]: adding a chatbot

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [maniyaom/Movie-Ticket-Booking#215]
### Feature Description

-

### Provide a detailed description of the feature

i want to add a chatbot which will be finetuned specific to the website ,
@maniyaom can you please assign me this task.

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by Yuvrajsinha24** [comment]
I can also help you to create a chat box on it

**Comment by maniyaom** [comment]
@Khizarshah01 Please handle this issue. There should be one button in bottom right corner of contact us page where user can access this chatbot.

**Comment by Khizarshah01** [comment]
@T-Rahul-prabhu-38  Regarding your enhancement issue, could you describe a bit more about the chatbot you're proposing? Specifically, what it will do and how it will benefit the project?

**Comment by T-Rahul-prabhu-38** [comment]
its a chatbot u find on the  bottom right of most websites , first ill train the bot on ur website , so it will know everything present in the website , eg: i recently did it on a online food order platform and the bot answered questions regarding to menu etc. So in doing so it will know all the movies present + bonus feature will be  u can find any actors movies by asking the bot.

**Comment by Khizarshah01** [comment]
@T-Rahul-prabhu-38 Thanks for the explanation! That sounds like a great feature, especially with the ability to find actors' movies by asking the bot.
Just a couple of questions before starting:
   - What tools or technology will you use to build the chatbot?
   - How will you keep the bot updated when new movies are added to the site?

**Comment by T-Rahul-prabhu-38** [comment]
1 -  there are couple of websites which will help me create one , then integration is done using JS.
2 - Its built on gpt4o so it will have data of any new movie released across globe , so it can answer whenever new movies are added to site and by asking if the website has the movie, it will go through to check if its present or not.

**Comment by Khizarshah01** [comment]
@T-Rahul-prabhu-38 I understand your idea, and it sounds great. However, since this project is still in its initial phase, using GPT-4, which is a paid service, might not be the best approach right now. There are many free ways to access new movie data, including actors' details, so it might be better to explore those alternatives.

For now, I suggest focusing on building a chatbot that works with the existing static data on the site. What do you think? Can you start by developing the bot to handle the current data, and we can explore more advanced features later? :)

**Comment by T-Rahul-prabhu-38** [comment]
oh nono
gpt4o is free for all.
