### ISSUE TITLE
[Feat]: ContactUS Form

### ISSUE THREAD

**Issue by Bhum-ika** [maniyaom/Movie-Ticket-Booking#221]
### Feature Description

A form can be added in the page to let user input their msgs and reach to you in a click from your website only

### Provide a detailed description of the feature

I would like to add a form in the Contact Us page with fields:
Name, email, Their Msg and a send button 

And also on the other hand, would add your contact details in more aligned way.

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by maniyaom** [comment]
@Bhum-ika Work on it, but will you be able to do it in tailwind CSS?

If you have any design in mind then share it here.

**Comment by Bhum-ika** [comment]
Ya sure

**Comment by Bhum-ika** [comment]
Hi @maniyaom 
![image](https://github.com/user-attachments/assets/36513346-31c9-4eba-8802-72675ea37bfb)

Please have a look on this issue. I ran into it when I ran the project

**Comment by Bhum-ika** [comment]
@maniyaom Please reply

**Comment by Bhum-ika** [comment]
@maniyaom please reply

**Comment by maniyaom** [comment]
You have to create .env file and add related content in that file please checkout Readme.md for more information.

**Comment by Bhum-ika** [comment]
Okay
