### ISSUE TITLE
[Feat]: Form Validation and Adding a default time for Listing movies

### ISSUE THREAD

**Issue by Akshithsaai** [maniyaom/Movie-Ticket-Booking#228]
### Feature Description

Form Validation and Default Time for Movie Shows

### Issues:
While Listing movie a Movie on Ticketify, The Form is not validated for most of the fields. 
example : Movie Language should not be a number, Ticket Price should not be a string. 
I have created a test movie with the ticket price as a string it shows insufficient Balance even though there is some balance in my account.

Also I propose to add a default movie Time Feature. 

### Solution
1. To implement form validation in listing the movies.
2. Changes to Movie Timings as shown below.

Please check screenshots.

### Current version: 
![image](https://github.com/user-attachments/assets/271445d1-03af-4597-8a71-015840c9cae0)
![image](https://github.com/user-attachments/assets/f9cd6c88-44e2-4887-b2ae-4ab3dc7143f1)
![image](https://github.com/user-attachments/assets/28056b5d-7fb6-4cce-a3a9-5f2f6268cf8a)

![image](https://github.com/user-attachments/assets/41af07c2-234b-48f6-b384-943fce510a88)

### Proposed Version
Validated Form  and 
![image](https://github.com/user-attachments/assets/12246511-de84-40ec-babb-47c07ee6354b)

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by maniyaom** [comment]
@Akshithsaai The "insufficient balance" message appears because the total cost of the ticket exceeds your current account balance. Please create another account, and that should resolve the issue.

**Comment by maniyaom** [comment]
Have you added any unit for price like "300 Rs." ? 

You just have to add the value in number only.

**Comment by Akshithsaai** [comment]
Yeah @maniyaom , currently the input is allowing to enter string values also . This is a major bug to be fixed for the functionality of the booking . 
So I am working on this form validation. I will be able to complete by today night.

**Comment by Akshithsaai** [comment]
@maniyaom I have Created a pull request on the issue. Its totally resolved. Please check it to merge.
