### ISSUE TITLE
[Feat]:  Navbar and Footer Background Color Mismatch

### ISSUE THREAD

**Issue by MuhammadAshraf23** [maniyaom/Movie-Ticket-Booking#245]
### Feature Description

Background Color of navbar and footer are not matching. 

### Provide a detailed description of the feature

The background colors of the navbar and footer are not matching, causing a visual inconsistency across the site. I propose adjusting the background color of either the navbar or footer to ensure both match for a more uniform design.

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by maniyaom** [comment]
@MuhammadAshraf23 Please share the screenshots and point out the difference. I think there is no difference in that.

**Comment by MuhammadAshraf23** [comment]
Sorry I made mistake
