### ISSUE TITLE
[Feat]: Implementation of a 404 Page Not Found

### ISSUE THREAD

**Issue by Hemant9808** [maniyaom/Movie-Ticket-Booking#263]
### Feature Description

A well-designed 404 page enhances user experience by reducing frustration and guiding users back to useful content.

### Provide a detailed description of the feature

The website currently lacks a custom 404 error page, which can lead to confusion for users who navigate to non-existent URLs. Users may encounter a generic error message, which is not user-friendly.
A custom 404 page should be implemented, featuring a friendly message explaining the error, a button to redirect users to the homepage, and links to popular sections or a search bar to help users find relevant content easily.

### Put here any screenshots or videos (optional)

![Screenshot 2024-10-10 224346](https://github.com/user-attachments/assets/2c5ccc1d-6385-44b1-b3e9-08ba1cbae725)

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by maniyaom** [comment]
@Hemant9808 Implement it but it should be in Tailwind CSS.

**Comment by Hemant9808** [comment]
> @Hemant9808 Implement it but it should be in Tailwind CSS.

Yes I will use tailwind

**Comment by Hemant9808** [comment]
i have implemented 404 page , please and merge my pull request @maniyaom @sanjay-kv @ayushijap

**Comment by Hemant9808** [comment]
I have made the 404 page responsive for all devices , please check my pull request #289 
@maniyaom
