### ISSUE TITLE
Adding Contributors page

### ISSUE THREAD

**Issue by TBorundia** [maniyaom/Movie-Ticket-Booking#275]
### Feature Description

I can add the option to navigate contributor page. I will show the github profile of all the contributors worked for the project. I will ensure to make the page UI similar to the theme and also responsive for all screens. It will directly fetch the data from the repository.

### Provide a detailed description of the feature

It will show,
Transparency: It shows transparency in the project's development and highlights the collaborative effort behind it.
Engagement: It helps build a community by encouraging more people to contribute and get involved.
Networking: It provides an opportunity for users to connect with contributors, potentially leading to more collaboration and support.

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by maniyaom** [comment]
@TBorundia Please checkout [Readme.md](https://github.com/maniyaom/Movie-Ticket-Booking/blob/master/README.md)

![image](https://github.com/user-attachments/assets/65177c6d-5a18-4648-8454-b2cd46bbf447)
