### ISSUE TITLE
Making A home page for the website

### ISSUE THREAD

**Issue by hritika2409** [maniyaom/Movie-Ticket-Booking#28]
<img width="935" alt="image" src="https://github.com/user-attachments/assets/8633d365-be85-4355-9aec-3bcd7f92bd5c">

**Comment by pavitraag** [comment]
I would like to work on this  Please assign it to me under gssoc.

**Comment by maniyaom** [comment]
@hritika2409 This is a duplicate issue. You can find the original here: #6
