### ISSUE TITLE
[Bug]: Unnecessary Margin on top 

### ISSUE THREAD

**Issue by krish2366** [maniyaom/Movie-Ticket-Booking#281]
### Bug Description

unwanted margin to the navbar

### Provide a detailed description of the bug

There's some margin to the top of the navbar
![Screenshot 2024-10-12 201437](https://github.com/user-attachments/assets/d3e3f6ca-7593-4cfe-a5b4-341c924eaeed)

### Expected Behavior

there should be no margin to the top

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this has not been reported yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by krish2366** [comment]
@maniyaom assign me this I'll fix it quickly

**Comment by maniyaom** [comment]
@krish2366 use tailwind css and complete it by today only.

**Comment by srishti023** [comment]
Assign me this issue i can do it within 1 hour!

**Comment by krish2366** [comment]
@maniyaom PR created please check and review it
