### ISSUE TITLE
Bad Responsiveness

### ISSUE THREAD

**Issue by SatyaJaiss** [maniyaom/Movie-Ticket-Booking#3]
![Screenshot 2024-10-01 182906](https://github.com/user-attachments/assets/d2fc71e1-6b5f-409f-a72b-86b5c8568964)

the responsiveness of the site needs improvement

**Comment by maniyaom** [comment]
@SatyaJaiss , I am assigning this task to you. However, another contributor is currently working on the Signup and Contact Us pages. Once those issues are resolved, I will notify you.

**Comment by SatyaJaiss** [comment]
can you help me i solved the issue, how can I submit it?

**Comment by SatyaJaiss** [comment]
I have made a PR, kindly review.

**Comment by ruchikakengal** [comment]
i want to work on it To give responsiveness to the webpage
