### ISSUE TITLE
[Bug]: "Dark/Light Mode Toggle Button Not Working in Navbar"

### ISSUE THREAD

**Issue by Ankul8471** [maniyaom/Movie-Ticket-Booking#313]
### Bug Description

The dark/light mode toggle button in the navbar is unresponsive, failing to switch between themes or update the button icon as expected.

### Provide a detailed description of the bug

The dark mode/light mode toggle button in the navbar is currently non-functional. Clicking on the button does not toggle between the dark and light themes as expected. This feature is critical to allow users to switch between light and dark modes for better usability and comfort, especially in different lighting conditions.

### Expected Behavior

When the toggle button is clicked:
The website should switch between light mode (default) and dark mode (dark background with light text).
The button icon should change from sun 🌞 (light mode) to moon 🌜 (dark mode) based on the current mode.
The user's preference should be saved in localStorage to persist across page reloads.

### What browsers are you seeing the problem on?

Chrome

### Put here any screenshots or videos (optional)

![,,](https://github.com/user-attachments/assets/c5bd1d16-3bf8-4192-a8ad-bc0f9a9cc244)

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this has not been reported yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Atul7307** [comment]
hey, 
please assign me this issue i handle this issue and create all website with dark mode

**Comment by Ankul8471** [comment]
@maniyaom  hello, i would like to work on it , please assign me

**Comment by Ankul8471** [comment]
@maniyaom Hello, I would like to work on it, please assign me...
