### ISSUE TITLE
Forgot Password Page is not working and Enhancement of SignUp page's UI 

### ISSUE THREAD

**Issue by SRV30** [maniyaom/Movie-Ticket-Booking#318]
please assign this work to me

**Comment by maniyaom** [comment]
There is no need of improvement in signup page. If you want you can implement sign up page.

**Comment by maniyaom** [comment]
You also need to implement forgot password functionality not just UI.

**Comment by maniyaom** [comment]
@SRV30 are you working on it?

**Comment by SRV30** [comment]
@maniyaom yes, thank you for assigning me

**Comment by SRV30** [comment]
@maniyaom kindly see my PR , and tell me if is it good or not. Thank You
