### ISSUE TITLE
[Feat]: Images on About us page

### ISSUE THREAD

**Issue by Vaishh18** [maniyaom/Movie-Ticket-Booking#327]
### Feature Description

I will add highquality images which goes with the theme and makes website more attrative

### Provide a detailed description of the feature

These current images are not going with the theme and are over expanding making the ui quite weak

![Screenshot (1122)](https://github.com/user-attachments/assets/1fdbcb27-8760-4396-b5b7-f9003faf208f)

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by shauryaq05** [comment]
I would like to add another feat into this feature

**Comment by Khizarshah01** [comment]
@Vaishh18 Please change the images to new ones that align with our theme. Please make sure the new images are optimized for size, since the current images are over 1 MB, which negatively impacts loading times.

**Comment by Vaishh18** [comment]
@Khizarshah01 yes sure!!

**Comment by Khizarshah01** [comment]
Go ahead!
