### ISSUE TITLE
[Bug]: Navbar Home Icon Click Not Functioning

### ISSUE THREAD

**Issue by amanver45** [maniyaom/Movie-Ticket-Booking#341]
### Bug Description

The home icon in the navbar does not redirect to the homepage when clicked.

### Provide a detailed description of the bug

When clicking the home icon in the navigation bar, the user is not redirected to the homepage as expected. This issue seems to occur across different browsers and prevents the user from easily navigating back to the homepage. The icon appears visually clickable, but there is no redirection or visible action upon clicking.

### Expected Behavior

The home icon should redirect the user to the homepage

### What browsers are you seeing the problem on?

Microsoft Edge

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/96c34b52-d525-4188-a97a-bf968dde665a

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this has not been reported yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by amanver45** [comment]
@maniyaom pls assign me this issue.

**Comment by DARSHANITRIPATHI** [comment]
Please assign this task to me.
