### ISSUE TITLE
[Feat] Adding animeted Pre Loader: 

### ISSUE THREAD

**Issue by AbhijitMotekar99** [maniyaom/Movie-Ticket-Booking#350]
### Feature Description

The new feature is an animated preloader that would display while the website is loading its contents. The preloader would help enhance user experience by providing a smooth and visually appealing loading indicator before the main content of the site is fully rendered.

### Provide a detailed description of the feature

The new feature is an animated preloader that would display while the website is loading its contents. The preloader would help enhance user experience by providing a smooth and visually appealing loading indicator before the main content of the site is fully rendered.

### Use Case

1. Initial Load Times: Users might experience slight delays due to larger assets or slow networks. The preloader would fill this gap, making the waiting time feel more fluid and professional.
2. First-Time Users: First-time users of the site may have slower load times as assets like images and scripts are fetched for the first time. The preloader would reassure them that content is being loaded.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/ab4e1fc8-54e5-4c2f-b58a-db67299b32af

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by Khizarshah01** [comment]
Thanks for the suggestion! However, I’ve decided to keep the website streamlined without an animated preloader to prioritize performance and simplicity. Closing this issue.
