### ISSUE TITLE
Update Testimonial Section to a Professional Carousel Slider

### ISSUE THREAD

**Issue by Sefukamil20R** [maniyaom/Movie-Ticket-Booking#352]
Current Testimonials 
![Screenshot (27)](https://github.com/user-attachments/assets/28ec5311-df8b-4a1e-9e0c-b725a4a180bf)
The current testimonial section, which uses a dropdown style, lacks a professional and engaging appearance. I propose updating the testimonial section to a carousel slider to create a more polished and modern user experience. This will include adding carousel controls for easy navigation and presenting testimonials in a visually appealing way, enhancing the overall aesthetic and usability of the website.
The proposed Testimonials 
![Screenshot (28)](https://github.com/user-attachments/assets/9453c7ac-55b2-4ca3-84f6-967904fc1aa5)

@maniyaom

**Comment by Akshithsaai** [comment]
@Sefukamil20R , Please contact the repo owner @maniyaom

**Comment by Sefukamil20R** [comment]
Ok, ThankYou

**Comment by Khizarshah01** [comment]
@Sefukamil20R This is a great idea for the testimonials! Would you like to work on this issue?

**Comment by Sefukamil20R** [comment]
Yes, please!

**Comment by maniyaom** [comment]
@Sefukamil20R , please ensure that the design you create is responsive.

**Comment by Sefukamil20R** [comment]
@Khizarshah01, Ok sure Thankyou

**Comment by Sefukamil20R** [comment]
@maniyaom , yeah I will

**Comment by Khizarshah01** [comment]
@Sefukamil20R any updates?

**Comment by Sefukamil20R** [comment]
@Khizarshah01 , @maniyaom ,
I have submitted the pull request now. Apologies for the delay

**Comment by Sefukamil20R** [comment]
yeah i am done , I have submitted the pull request , check it out please

**Comment by Khizarshah01** [comment]
@Sefukamil20R , could you pull the latest changes from the main branch into your local repo and push your updates again? Your repo is currently behind the main branch.

**Comment by Sefukamil20R** [comment]
@Khizarshah01 , I checked it again , I've merged the latest changes from master into my sefina-testimony branch and pushed everything. Is there anything else you need from me to finalize the pull request?

**Comment by Khizarshah01** [comment]
#394 PR Merged
