### ISSUE TITLE
[Feat]: ADDITION OF FEEDBACK SECTION

### ISSUE THREAD

**Issue by shriyadindi** [maniyaom/Movie-Ticket-Booking#356]
### Feature Description

FEEDBACK SECTION

### Provide a detailed description of the feature

I would like to add a feedback section for the website.

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by Khizarshah01** [comment]
@shriyadindi  Thank you for the suggestion! I think it's a good idea. Would you like to work on this issue?

**Comment by shriyadindi** [comment]
@Khizarshah01 yes..

**Comment by Khizarshah01** [comment]
@shriyadindi , I have assigned you this issue. If you need any help, feel free to ask.
