### ISSUE TITLE
improve footer of this page 

### ISSUE THREAD

**Issue by jayanththalla** [maniyaom/Movie-Ticket-Booking#36]
improve the ui of the footer 
![image](https://github.com/user-attachments/assets/96222291-7087-4003-8f8d-5f88ee4e435c)
please assign me @pa
under gssoc and hacktobefest

**Comment by maniyaom** [comment]
@jayanththalla This appears to be a duplicate of an existing issue. Before raising a new issue, please make sure to check the issue section to avoid duplicates.

Reference: Issue 22
