### ISSUE TITLE
 Improve Footer Design for Better Usability and Aesthetics

### ISSUE THREAD

**Issue by NirajD04** [maniyaom/Movie-Ticket-Booking#361]
### Feature Description

Footer Enhancement

### Provide a detailed description of the feature

The current footer could be improved to enhance both functionality and visual appeal. A well-designed footer can provide important navigation links, contact information, and other useful content, making it an essential part of the website's overall user experience.

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [ ] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by NirajD04** [comment]
Please assign this issue to me

**Comment by Khizarshah01** [comment]
#348 duplicate issue!
