### ISSUE TITLE
[Feat]: update the navbar design

### ISSUE THREAD

**Issue by priyashuu** [maniyaom/Movie-Ticket-Booking#380]
### Feature Description

I want to redesign the navbar to improve its visual appearance and functionality.

### Provide a detailed description of the feature

The navbar redesign should enhance the overall user experience by making it more modern, functional, and responsive. The new design should prioritize a clean and minimalistic layout with updated styling, including changes to the color scheme, fonts, hover effects, and alignment. Key features such as the search bar, profile icon, and hamburger menu should be seamlessly integrated for both desktop and mobile views. Additionally, the navbar should adapt to different screen sizes, maintaining its aesthetic and usability across all devices.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/6ea41187-049a-484c-be50-68c798379bde

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this feature has not been proposed yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this feature (optional)

**Comment by adityalaxkar123** [comment]
Me a GSSOC'24 extended member can you assign it to me

**Comment by priyashuu** [comment]
please assign this issue to me

**Comment by maniyaom** [comment]
I want a responsive navbar that matches the current design of the navbar on the website.

**Comment by priyashuu** [comment]
Please assign this issue to me under GSSoC and add the levels also

**Comment by priyashuu** [comment]
Please assign this issue to me under GSSoC and add the levels also

**Comment by priyashuu** [comment]
Please assign this issue to me under GSSoC and add the levels also @maniyaom

**Comment by priyashuu** [comment]
Please assign this issue to me under GSSoC and add the levels also @maniyaom
