### ISSUE TITLE
Hamburger Menu

### ISSUE THREAD

**Issue by TanmayKalra09** [maniyaom/Movie-Ticket-Booking#39]
on the right side of the login button, we can add the hamburger menu through which users can see options like rewards, notifications and Your orders

Please assign me this issue under GSSOC Extended and Hacktoberfest :)

**Comment by maniyaom** [comment]
@TanmayKalra09 We are not providing any rewards to the users. Regarding notifications, if you want to add a notifications button, you will also need to create a separate notifications page for that.

Let me know if you can work on this issue or if you have any suggestions.

**Comment by TanmayKalra09** [comment]
Sure, I will add a notification button in the navbar, which will redirect the user to a different page.
