### ISSUE TITLE
[Bug] : Homepage not responding 

### ISSUE THREAD

**Issue by Prisha1407** [maniyaom/Movie-Ticket-Booking#395]
### Bug Description

homepage when clicked not respondes

### Provide a detailed description of the bug

![image](https://github.com/user-attachments/assets/85c5458c-4fbb-4706-8307-46d332f442f3)

### Expected Behavior

homepage to be designed 

### By submitting this issue, you agree to

- [X] I agree to follow this project's Code of Conduct
- [X] I’ve read all the issues in the issue section, and this has not been reported yet.

### Other Information

- [X] I'm a GSSoC '24 Extended contributor
- [X] I'm a Hacktoberfest '24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Prisha1407** [comment]
i want to work on this

**Comment by Prisha1407** [comment]
@maniyaom pls assign this to me

**Comment by maniyaom** [comment]
@Prisha1407 You have to login for accessing Home page.
