### ISSUE TITLE
Add a feature in the navbar to show tickets directly to the user

### ISSUE THREAD

**Issue by rishabhrawat05** [maniyaom/Movie-Ticket-Booking#4]
Hi! @maniyaom 
The project is overall good but there is an issue with the ticket section. If I bought a ticket it tracks me back to the home page and there is no option to view the tickets I have bought, I have to go through the account section and then click on the movie title to view the ticket which is not good for the ease of user and also the user will not be happy with the app

Here I have attached the screenshot of the flow of how I managed to book and view tickets
![Screenshot (186)](https://github.com/user-attachments/assets/9f787e64-c00c-4dfc-87db-5c1478cfb293)

![Screenshot (185)](https://github.com/user-attachments/assets/0dd34536-6f7a-47c1-925f-93425023eff1)
![Screenshot (187)](https://github.com/user-attachments/assets/b3afe19c-d1d4-4e02-9c52-182e2ec275bf)
![Screenshot (188)](https://github.com/user-attachments/assets/fd16c363-507f-46ec-895b-df22cfb5b521)

So, I want to add a feature in the navbar where a user can easily access the ticket, and after booking, it will redirect to the view ticket page.

Can you please assign this issue to me

**Comment by maniyaom** [comment]
@rishabhrawat05 ,One more suggestion: after a ticket is booked, the user should be redirected to the ticket they just purchased.

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me
