### ISSUE TITLE
Suggest Using Shadcn for Improved UI Experience

### ISSUE THREAD

**Issue by tejasbenibagde** [maniyaom/Movie-Ticket-Booking#40]
### Enhancement Proposal
I would like to propose the integration of Shadcn UI components into the Movie Ticket Booking application to enhance the overall user experience and visual appeal.

### Rationale
The current UI could benefit from a more modern and cohesive design. By utilizing Shadcn, we can achieve a more polished look that aligns with contemporary design trends. 

### Suggested Changes
- Integrate Shadcn UI components to replace existing elements for a more unified design.
- Implement responsive layouts to ensure usability across different devices.
- Enhance accessibility by following best practices in UI design.

### Example UI
For inspiration, you can refer to this example UI from Shadcn: [Music UI Example](https://ui.shadcn.com/examples/music). This showcases how a well-structured UI can significantly improve user interaction.

### Benefits
- **Improved Aesthetic**: A modern design will make the application more visually appealing to users.
- **Theming**: It will be easier to implement the dark and light mode.
- **Consistency**: Utilizing a UI library ensures a consistent look and feel across the application.
- **Enhanced User Experience**: A better UI can lead to increased user satisfaction and engagement.

### Additional Context
I believe that adopting Shadcn can greatly enhance the overall quality of the application and make it stand out in the competitive landscape of ticket booking applications.

**Comment by maniyaom** [comment]
@tejasbenibagde Someone is currently working on the homepage. Could you please hold off for now? I will let you know once it's fixed.

**Comment by tejasbenibagde** [comment]
Ok

**Comment by tejasbenibagde** [comment]
Can you add the level 2 or 3 label cause I'll be adding the theming like dark mode light mode and working on almost everything in the application.

**Comment by maniyaom** [comment]
@tejasbenibagde Start working on Login & Sign Up page for now. Just make sure you don't mess up with the functionality of that pages.

additionally don't make any changes to any other pages.
