### ISSUE TITLE
 improving the README file

### ISSUE THREAD

**Issue by adityakalburgi** [maniyaom/Movie-Ticket-Booking#41]
Hi!
I'd like to contribute by improving the README file. Could you please assign this issue to me? also add labels of gssoc-ext and hacktoberfest Thanks!

**Comment by maniyaom** [comment]
@adityakalburgi This appears to be a duplicate of an existing issue. Before raising a new issue, please make sure to check the issue section to avoid duplicates.

Reference: Issue 16
