### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by tanish35** [maniyaom/Movie-Ticket-Booking#42]
Currently no verification mail is being sent to verify whether the email belongs to the user or not which may lead to spammy requests. Pls assign this to me under hacktoberfest

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me

**Comment by tanish35** [comment]
@lakshyeahh can you open a new issue and work with phone verification?

**Comment by tanish35** [comment]
#64 Has been added

**Comment by lakshyeahh** [comment]
yes sir phone verification sound cool too. should i continue adding it?

**Comment by maniyaom** [comment]
@lakshyeahh Yes, you can raise issue and work on that
