### ISSUE TITLE
Ading a explore new "explore" block  in te nav bar

### ISSUE THREAD

**Issue by yeshwanth-ds** [maniyaom/Movie-Ticket-Booking#46]
To implement this Explore Block for displaying a list of recently released movies in theaters, here's a clean breakdown of the features, benefits, and instructions for requesting the task assignment under GSSoC and Hacktoberfest.

Features:
Movie Poster: Each movie card will display a visually appealing movie poster.
Movie Name: Prominently display the title of the movie.
Cast: List the main actors and directors involved in the movie.
Brief Description: Provide a concise overview of the movie's plot to attract user interest.
Critics Rating: Include a rating system (stars or numeric) based on reviews from popular critics.
Get Tickets Button: A call-to-action button for users to buy tickets, which can link to an external or integrated ticketing service.
Genre-Based Filtering: Let users filter movies by genre, making it easy for them to find movies they prefer.
Responsive Design: Ensure the page is mobile-friendly and matches the theme of the main website for a seamless experience.

Benefits:
Engagement: Users will spend more time on the site browsing movies they’re interested in.
Easy Navigation: By offering genre filters, users can quickly find the movies that suit their preferences.
Revenue Potential: The "Get Tickets" button can generate revenue or leads for ticketing partners.
Improved Aesthetics: Including visually appealing elements like movie posters will enhance the overall user experience.
Seamless Integration: Matching the theme with the main page ensures continuity and a professional look.

Request for Admin Assignment:
Please assign this task under the GSSoC-EXT and Hacktoberfest tags. It’s a great opportunity for contributors to work on a high-visibility feature, which will enrich the user experience and align with the goals of open-source contributions. By maintaining consistency with the main page's theme, the Explore Block will integrate smoothly and boost user engagement. 

![Screenshot 2024-10-02 153526](https://github.com/user-attachments/assets/6a1cdc82-d58d-47f1-83b6-3880675b97d4)

**Comment by maniyaom** [comment]
@yeshwanth-ds by clicking on movie's poster you can find all the details you mentioned here.

**Comment by yeshwanth-ds** [comment]
@maniyaom So once you clicked on explore block this will be next to "Home" block in the nav bar, the explore page will open. This explore page will contain list of all all the recent releasd and upcoming movies. Where each movie div will contains the movie poster, review, name, cast, genera and a get ticket button.
Let me kown if there is any clarifiaction or enhancement in this task.

**Comment by maniyaom** [comment]
@yeshwanth-ds Okay let's see.

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me

**Comment by maniyaom** [comment]
@yeshwanth-ds Closing this issue due to 5 days of inactivity. Feel free to reopen if needed.
