### ISSUE TITLE
Showing live Status of Bus and Train

### ISSUE THREAD

**Issue by sejals23** [maniyaom/Movie-Ticket-Booking#51]
The webpage integrates live GPS data through APIs like Google Maps or local transit services. This dynamic feature updates automatically at regular intervals, providing users with real-time information on the exact locations of buses and trains. Additionally, users can access route details, schedules, and receive alerts about any service interruptions, making commuting easier and more predictable. Overall, this live tracking system enhances the public transportation experience by providing transparency and convenience to commuters.

**Comment by maniyaom** [comment]
@sejals23 This is a movie ticket booking website no need of live status of bus and train. If you have any other ideas related to that please let me know.
