### ISSUE TITLE
 Add 'Offers' Section to Navigation Bar, To increase the User Engagement.

### ISSUE THREAD

**Issue by SCR01** [maniyaom/Movie-Ticket-Booking#53]
#### Description:
We need to add an **' Offers' section** to the navigation bar of the movie booking ticket website to highlight current promotions and discounts for users.

#### Why is this important?
- This section will attract users to take advantage of ongoing offers, increasing engagement and ticket sales.
- It will provide a dedicated space for users to easily find promotions and special deals.

#### Comment:
- The 'Offers' section should be clearly visible in the navigation bar.
- It should link to a dedicated page listing all current offers, including terms and conditions.
- Ensure the design is consistent with the existing navigation style and easy to access.

Example:
![image](https://github.com/user-attachments/assets/dc689db7-4738-4bbf-9153-b15e3a38fdc8)

**Comment by maniyaom** [comment]
@SCR01 any update? Reply me ASAP

**Comment by SCR01** [comment]
@maniyaom yeah i will do it before 6am.
