### ISSUE TITLE
A filter for the genre of the movie can be added like action, horror for search

### ISSUE THREAD

**Issue by Nikitaganeshbabu** [maniyaom/Movie-Ticket-Booking#54]
Description: A filter for the genre can be added like action, horror for search

![image](https://github.com/user-attachments/assets/d3fe5380-9ad0-48a5-bc63-86f8d801e7c1)

![image](https://github.com/user-attachments/assets/eb4efe88-faca-46aa-977c-9298ef6d7d9f)
like this 

The posters are fetched from firebase . A column for genre can be added.

**Comment by RIYA-YADAV-19** [comment]
I noticed that adding a genre filter (like action, horror, etc.) to the movie search feature could improve the user experience by making it easier for users to find movies they prefer. I'd like to take on this task and implement the filter, as I believe it will enhance the overall functionality of the website. Could I be assigned this issue to work on?

**Comment by RIYA-YADAV-19** [comment]
I have also raised a issue on background of the website if you can check please

**Comment by Nikitaganeshbabu** [comment]
Thank you for assigning me I'll work on it and update

**Comment by Nikitaganeshbabu** [comment]
I want to add more movie posters to  the database ?

**Comment by maniyaom** [comment]
> I want to add more movie posters to the database ?

You can sign up as an admin and then click on 'List Your Show' in the navbar to add a new movie poster.

**Comment by Nikitaganeshbabu** [comment]
if i click on List your shows it is navigated to Home page ?

**Comment by maniyaom** [comment]
@Nikitaganeshbabu Closing this issue if you are not working on it. Let me know what's the status?

**Comment by maniyaom** [comment]
@Nikitaganeshbabu Submit it by tomorrow otherwise I have to close this issue.
