### ISSUE TITLE
Update the design of the about us page

### ISSUE THREAD

**Issue by Bz14** [maniyaom/Movie-Ticket-Booking#55]
- I want to update the design of the about us page with the same content to make it more user friendly.

**Comment by maniyaom** [comment]
@Bz14 I want to redesign the whole page. Let me know if you are interested and please give image of design if you have any specific idea.

**Comment by Bz14** [comment]
I am interested. In terms of the about us page i want to make it more descriptive and user friendly instead of plain text and image. 
For instance something like this for what we offer section:
![whatweoffer-1](https://github.com/user-attachments/assets/ab290093-7ef7-4b2a-ad2d-2f2d07517b39)

**Comment by maniyaom** [comment]
@Bz14 there is no requirement of such kind of designs. Please focus on other issues which are more important.
