### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by shreyad2806** [maniyaom/Movie-Ticket-Booking#56]
I can make a personalized logo for your website to make it look more professional.
Please assign me this issue under gssoc'24 EXTENDED and hacktoberfest

**Comment by SHUBHAG100520** [comment]
Can i too work on logo.

**Comment by maniyaom** [comment]
@shreyad2806 what's the update? If you can't do this let me know.

**Comment by shreyad2806** [comment]
Almost done. I'll be submitting it by today .
