### ISSUE TITLE
Add dark toggle button

### ISSUE THREAD

**Issue by shreyad2806** [maniyaom/Movie-Ticket-Booking#57]
The website does not have a dark mode, which is a highly requested feature for users who prefer lower brightness settings.
I can implement a dark mode toggle with smooth transitions between light and dark themes.
Please assign me this issue under gssoc'24 EXTENDED and hacktoberfest

**Comment by sambedan1** [comment]
please assign to me

**Comment by shreyad2806** [comment]
completing by tomorrow

**Comment by maniyaom** [comment]
@shreyad2806 any update?

**Comment by coderashhar** [comment]
can you assign this to me also , I'll give you my version of dark mode and then you can select whichever version you like more

**Comment by maniyaom** [comment]
@coderashhar another contributor raised this issue before you, so I need to give them priority.
