### ISSUE TITLE
[Add]: Privacy Policy Page

### ISSUE THREAD

**Issue by Shiv13jm** [maniyaom/Movie-Ticket-Booking#58]
### Bug Report: Footer Section
Hey @maniyaom 
**Description:**
The footer section currently contains navigation links similar to the navbar, including "About Us", "Home", "Contact Us", and "Login". This is not the intended design for the footer.
**Expected Behavior:**
The footer should contain different details, such as:
- Company information
- Privacy policy
- Terms of service
- Social media links

I will update the footer section to include the appropriate details:
1. Remove the current navigation links.
2. Include links to the privacy policy and terms of service.

Please assign this issue to me under gssoc'24 extended with label gssoc'24 and hacktoberfest. Thanks!!
You can also label the level.
![Screenshot 2024-10-02 185938](https://github.com/user-attachments/assets/2fb41f11-b1e1-4dfc-87dd-10ba7a8e2331)

**Comment by maniyaom** [comment]
@Shiv13jm Are you going to make terms of service and privacy policy page?

**Comment by Shiv13jm** [comment]
@maniyaom I will be adding a link to a new page " Privacy Policy " . The website owner can make Privacy Policy according to the privacy rules and regulations.

**Comment by anadisharma121** [comment]
@maniyaom I would like to add sections like "help" , "places where service is available", "customer care", "news letter", "partner with us" etc. in the footer section to make the website look more appealing and genuine. Please assign this to me under gssoc'24 extended and hacktoberfest. Thanks

**Comment by maniyaom** [comment]
@Shiv13jm adding a simple link in footer is not a big deal. For that i can assign you this issue to you but i will not be able to give label hacktoberfest-accepted or gssoc-ext.

**Comment by Shiv13jm** [comment]
@maniyaom Thank you  for letting me know that !! Would you like to share your thoughts, like what can I add more to get 'hacktoberfest-accepted' or 'gssoc-ext' label ?

**Comment by maniyaom** [comment]
@Shiv13jm You have to create privacy policy & terms & condition page.

**Comment by maniyaom** [comment]
@Shiv13jm are you working on it?

**Comment by Shiv13jm** [comment]
I am sorry . I am busy because of college commitments. You can assign it to someone else. Thank you!

**Comment by anadisharma121** [comment]
@maniyaom  I can create privacy policy & terms and condition page. Please let me know if it would count as worthy contribution in the "hacktoberfest" or "gssoc-extd".

**Comment by maniyaom** [comment]
@anadisharma121 assigned.

**Comment by anadisharma121** [comment]
@maniyaom Thank you for showing believe in me. I'll try my best to deliver as per the need.

**Comment by maniyaom** [comment]
@anadisharma121 You just need to create privacy policy and terms & conditions page. No need to modify footer. another contributor is converting footer to tailwind css he will add theses links.

**Comment by maniyaom** [comment]
@anadisharma121 what's the update on this?

**Comment by anadisharma121** [comment]
@maniyaom I was busy due to some college stuff, I'll update soon, still working on it.
