### ISSUE TITLE
Testimonials and frequently asked questions

### ISSUE THREAD

**Issue by BVaishnavi15** [maniyaom/Movie-Ticket-Booking#61]
Including testimonials and frequently asked questions in about us section
Please assign me this issue under gssoc'24 EXTENDED, hacktoberfest and give me the level

**Comment by maniyaom** [comment]
@BVaishnavi15 You have to add FAQs and testimonals by your self I will not provide anything.

**Comment by BVaishnavi15** [comment]
okay. can you please give me level

**Comment by maniyaom** [comment]
> okay. can you please give me level

I will give the level after reviewing your PR.

**Comment by BVaishnavi15** [comment]
ok

**Comment by Abhi0049k** [comment]
@maniyaom, Can you assign this issue to me?

**Comment by maniyaom** [comment]
> @maniyaom, Can you assign this issue to me?

@Abhi0049k sorry, I can't since you didn't raise the issue first.

**Comment by maniyaom** [comment]
@BVaishnavi15 you code has error that you have not imported "useState".

replace first line to this --> import React, { useEffect, useState } from 'react';

**Comment by maniyaom** [comment]
@BVaishnavi15 please when you raise pr make sure it is running without any errors.

**Comment by BVaishnavi15** [comment]
I'm sorry about it. I will make sure.

**Comment by maniyaom** [comment]
@BVaishnavi15 do recommanded changes and Raise another PR. make sure you work on updated repository.

**Comment by BVaishnavi15** [comment]
okay
