### ISSUE TITLE
Footer issue

### ISSUE THREAD

**Issue by KAmaL-senpai** [maniyaom/Movie-Ticket-Booking#66]
In the Home page the footer should be at the button but it is not leaving a blank space. Assign me this issue label- Gssoc2024 hacktoctober 2024.

![Screenshot (230)](https://github.com/user-attachments/assets/eb0e262c-144c-4892-84aa-4bb7765e669f)

**Comment by sambedan1** [comment]
I will review the footer layout to identify any alignment, styling, or functionality problems. This includes ensuring all links work correctly, elements are properly aligned, and the overall design matches the website's aesthetic.

Please assign this task to me so I can fix the footer issues!

**Comment by maniyaom** [comment]
@KAmaL-senpai I can't see any major issues with the footer.
![image](https://github.com/user-attachments/assets/4d799bcf-f3b7-4402-b32d-10955d4a7d55)
