### ISSUE TITLE
subheading visible in header on scrolling

### ISSUE THREAD

**Issue by riyaaryan2004** [maniyaom/Movie-Ticket-Booking#67]
### Description
Poor CSS
In signup page subheading is visible in header area. 
It should not be visible .
I want to fix this issue.
![Screenshot 2024-10-02 222748](https://github.com/user-attachments/assets/4fa716e2-7f09-4099-b68a-62bb507d389b)

**Comment by maniyaom** [comment]
@riyaaryan2004 any update on this?

**Comment by riyaaryan2004** [comment]
@maniyaom 
 yes ..actually ..I have already requested a PR on firebase #87 
So I am waiting for it to be merged to update Nav Bar issue..
U can tell me if u want me to update directly on my branch.
Or in fresh branch?

**Comment by riyaaryan2004** [comment]
I have fixed this issue in a clone of main branch...
Unfortunately I am not able to create another fork. so please merge the previous PR so that I can create new fork from main branch and reflect my changes..
![Screenshot 2024-10-04 001925](https://github.com/user-attachments/assets/07963fbb-9546-4eb8-984f-dab61d397857)

**Comment by maniyaom** [comment]
@riyaaryan2004 Okay, will do it by tomorrow.
