### ISSUE TITLE
Fixing screen orientation issue for different devices

### ISSUE THREAD

**Issue by DuckStruggles** [maniyaom/Movie-Ticket-Booking#68]
The navbar may need some responsiveness fixations. Please let me do this task!
![Screenshot 2024-10-02 225004](https://github.com/user-attachments/assets/7aed3e92-933a-4854-989d-cc02d67b22d8)

**Comment by maniyaom** [comment]
@DuckStruggles Another contributor is already working on making the navbar responsive. Please work on any other issues.
