### ISSUE TITLE
non sticky header &firebase authentication

### ISSUE THREAD

**Issue by riyaaryan2004** [maniyaom/Movie-Ticket-Booking#7]
### Issues
1. The header in the movie-ticket-booking-five project does not remain fixed at the top of the viewport while scrolling, leading to a poor user experience. When users scroll down the page, the header disappears, making navigation difficult.
2. There is no option for login/signup via google.

### Expected Behavior :
The header should remain sticky at the top of the viewport while scrolling, allowing users to easily access navigation links.
user don't have to enter email and password everytime they visit the website.
user can login without password if their registered gmail account is already logged in their device.

### Solution
1. I would like to work on this issue and implement a fix for the sticky header
2. I will add google firebase authentication.

### Screenshots
![image](https://github.com/user-attachments/assets/a0b794ea-2a58-4b53-b5c3-0fd370de1927)

![Screenshot 2024-10-01 203646](https://github.com/user-attachments/assets/7019238f-c227-42a0-9b05-4ab302d63c9a)

### Checklist

- [x]  I have checked the existing issues
- [x]  I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [x]  I'm a GSSoC'24-Extd contributor
- [ ]  I'm a Hacktoberfest'24 contributor
- [x]  I am willing to work on this issue (optional)

**Comment by maniyaom** [comment]
@riyaaryan2004 It's perfectly fine if the header is non-sticky, but you can add signup/login with google option.

**Comment by riyaaryan2004** [comment]
Thank you for assigning this issue to me.. I am working on that.

**Comment by lakshyeahh** [comment]
im interested please assign me, ill share my proposed solution as soon as u ping me

**Comment by riyaaryan2004** [comment]
@maniyaom 
In the original website ....there is an css issue ...sub heading is visible in header on scrolling.
can I fix that too?
![Screenshot 2024-10-02 222748](https://github.com/user-attachments/assets/6ce48e99-abdd-4080-be5c-5d70b0a1fa1e)
