### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by devarsheecodess** [maniyaom/Movie-Ticket-Booking#70]
The footer looks very basic with a lot of loopholes. @maniyaom , assign this task to me. I will improve the footer to next level. Also add gssoc-extd labels to this issue. Thank you

**Comment by Khushi-51** [comment]
I propose enhancing the footer section of the Ticketify website to improve both functionality and visual appeal. Here are the key areas I plan to focus on:

Design Consistency: I will ensure that the footer aligns with the overall website design by using consistent colors, fonts, and spacing.

Clear Call to Action: Adding visually distinct buttons for social media links and navigation items will improve user interaction.

Responsive Design: I will optimize the footer layout for various screen sizes to ensure it looks great on mobile, tablet, and desktop devices.

Additional Information: Consider including important links such as Privacy Policy, Terms of Service, or a newsletter signup to enhance user engagement.

These enhancements will provide users with a more enjoyable experience and a clearer navigation path. Please assign this task to me under GSSOC'24 Extended and Hacktoberfest. I’m excited to contribute to this project!
![f1](https://github.com/user-attachments/assets/79798cef-9a50-406f-abd5-7ae414878783)

**Comment by krish2366** [comment]
@maniyaom I am proficient with tailwind I can do it for you. please add the gssoc-extended label . That would be appreciated.
So you can  assign me this .

**Comment by akankshagoel28** [comment]
> @devarsheecodess I am planning to migrate to tailwind CSS. would you like to work on that? Can you create the responsive footer using tailwind css?

hi @maniyaom I will work on migrating the setup to tailwind if you assign it to me

**Comment by maniyaom** [comment]
@krish2366 Sure, you can start working on that.

@akankshagoel28 Please raise any other issues to work on. I assign tasks on a first-come, first-served basis.

**Comment by maniyaom** [comment]
@krish2366 what happened?

**Comment by krish2366** [comment]
Sorry about that, will complete it till Wednesday, my exams were there and I was sick. I'll definitely do it, that I can assure you

**Comment by maniyaom** [comment]
@krish2366 ok no worries.

**Comment by krish2366** [comment]
@maniyaom just created a PR , you can review and merge it.
