### ISSUE TITLE
Make home page

### ISSUE THREAD

**Issue by shivamy009** [maniyaom/Movie-Ticket-Booking#71]
make home page

please assign me to fix it

**Comment by maniyaom** [comment]
@shivamy009 It is already there. You can see all the movie posters on Home page.

**Comment by shivamy009** [comment]
> @shivamy009 It is already there. You can see all the movie posters on Home page.

I want to add home page when user is not registered or login 

It is like making hero section

**Comment by maniyaom** [comment]
@shivamy009 can you share the sample design?

**Comment by shivamy009** [comment]
> @shivamy009 can you share the sample design?

![Screenshot 2024-10-03 192954](https://github.com/user-attachments/assets/6daa73de-6064-47b2-a994-12d214918ed7)
like this i can modify on the basis that it is a movie ticket booking website

**Comment by maniyaom** [comment]
@shivamy009 Ok

**Comment by shivamy009** [comment]
> @shivamy009 Ok

can i work on it

**Comment by maniyaom** [comment]
@shivamy009 Yes, I’ve already assigned it to you.

**Comment by Tanyashri** [comment]
@shivamy009 Can we work on this together? I'd love to contribute for designing of home page. @maniyaom assign me this issue! I'd be glad to contribute.
Thank you.

**Comment by maniyaom** [comment]
@shivamy009 any update?
