### ISSUE TITLE
navigation bar underline hover effect

### ISSUE THREAD

**Issue by Krishnamverma951** [maniyaom/Movie-Ticket-Booking#72]
https://github.com/user-attachments/assets/1ef9f709-5af2-43b7-901a-e42c05c8f84d

i have use  in my website

in the navbar do not have hover effects, making them feel less interactive. I can add smooth hover transitions 
Please assign this issue to me under gssoc'24 EXTENDED with label gssoc'24 and hacktoberfest.

**Comment by Krishnamverma951** [comment]
help wanted

**Comment by Krishnamverma951** [comment]
please help  me index html  not open 
![image](https://github.com/user-attachments/assets/319d2bc0-53d5-49a3-bc88-cd8c96f139e5)
please solve my problem

**Comment by maniyaom** [comment]
@Krishnamverma951 Are you working with React Js for the first time?

**Comment by Krishnamverma951** [comment]
https://www.linkedin.com/in/krishnam-verma-65a644262?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app 

Please   dm me on linkedin

**Comment by Krishnamverma951** [comment]
Sir I have referred to the readme.md file and i have done the steps that needed to be done but as a beginner I am facing some difficulty for inital setup i have run the npm start command and the server gets start but still with a blank screen with this error in console 
Uncaught FirebaseError: Firebase: Error (auth/invalid-api-key).
    at createErrorInternal (assert.ts:152:1)
    at _assert (assert.ts:177:1)
    at Component.instanceFactory (register.ts:72:1)
    at Provider.getOrInitializeService (provider.ts:318:1)
    at Provider.initialize (provider.ts:242:1)
    at initializeAuth (initialize.ts:66:1)
    at getAuth (index.ts:83:1)
    at ./src/context/firebase.js (firebase.js:21:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:22:1)
    I want to know that .env file is not present. so do we have to generate our own API key through firebase and make our own .env file. Please help me in solving it

**Comment by maniyaom** [comment]
you have to create .env file and add all the required values in that. File content is given in Readme.md

**Comment by Krishnamverma951** [comment]
Please help me  sir I am beginner  how to create env file

**Comment by maniyaom** [comment]
@Krishnamverma951 I can't help you with everything. This is not that big task.

**Comment by KarthikSbrshB** [comment]
@maniyaom I can implement this. Please assign the issue to me.
