### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by kundana29** [maniyaom/Movie-Ticket-Booking#75]
i want to Fix the issue where the login page appears on both the Home and Login pages. Ensure the Home page displays a background image, a welcome description, and a footer with contact information. The Login page should remain separate. Add appropriate links in the header to navigate between the Home and Login pages
![Screenshot 2024-10-03 091436](https://github.com/user-attachments/assets/791d2f44-66c6-4ec4-8a4e-9f3b57fa5722)

**Comment by maniyaom** [comment]
@kundana29 another contributor is working on that please check issue section first before raising any issues.
