### ISSUE TITLE
Phone-Verification

### ISSUE THREAD

**Issue by lakshyeahh** [maniyaom/Movie-Ticket-Booking#76]

**Comment by lakshyeahh** [comment]
#120 I have raised the pr. For OTP verification you have to either enable yourself in the firebase console or provide me with the credentials to modify it accordingly. Thank you.

**Comment by maniyaom** [comment]
@lakshyeahh you have to mention this issue in that PR.

**Comment by lakshyeahh** [comment]
Done Sir. Please look into it.

**Comment by maniyaom** [comment]
@lakshyeahh there are some issues with your code. any update?

**Comment by lakshyeahh** [comment]
yes sir 
will update the pr by eod
