### ISSUE TITLE
Email Verification issue

### ISSUE THREAD

**Issue by KomalMaurya** [maniyaom/Movie-Ticket-Booking#77]
![image](https://github.com/user-attachments/assets/00875924-0a62-4efe-8d1c-a5bc11cd2fcc)
When I writing my email, it is not telling me if it's email or just random text....in email input box!
I want to correct that issue in order to avoid fake signup/Login attempts!

Name : Komal Maurya
Role : Contributor in GSSoC'24
GitHub Profile Link : https://github.com/KomalMaurya
@maniyaom Please assign this issue to me!

**Comment by maniyaom** [comment]
@KomalMaurya Only registered emails will be allowed to log in, so there's no need to check whether the email is valid or not.

**Comment by Cgarg9** [comment]
Can i work on this issue?

**Comment by maniyaom** [comment]
@KomalMaurya will you able to fix it? If not i have to assign it to others.

**Comment by KomalMaurya** [comment]
@Cgarg9 Go ahead! I was just created an issue to guide students in my community to go into open source....You can work on it!

**Comment by maniyaom** [comment]
@Cgarg9 assigned.

You don't need to check whether the email exists or not; simply validate the format of the email field.

**Comment by Cgarg9** [comment]
Hi. The email validation is already there once you click on the login/signup button.

**Comment by maniyaom** [comment]
> Hi. The email validation is already there once you click on the login/signup button.

If I input example.gmail.com, it is not a valid email format. You need to validate that.

**Comment by Cgarg9** [comment]
Hi. PR raised. Kindly verify and suggest any changes required
