### ISSUE TITLE
Bug Fixes : List Your Movie component

### ISSUE THREAD

**Issue by Akshithsaai** [maniyaom/Movie-Ticket-Booking#78]
#### 1. Movie Duration not in proper format 
![image](https://github.com/user-attachments/assets/aeb7a355-b04c-49aa-a7f8-c7cf39e44dcd)
#### 2. Lisiting Duration getting effecting due to Issue 1
![image](https://github.com/user-attachments/assets/e9dcfb1f-cf74-4054-af42-2d695139dcdb)
#### 3. (minor issue) Required Field getting mixed up with the color. I want to upgrade it something noticeable. 
![image](https://github.com/user-attachments/assets/bb4664f1-1161-4f6a-8b7a-fbbeab04e17d)

I would Like to work on this issues @maniyaom . Please Assign it to me.
Please Add only gssoc-extd tag

**Comment by maniyaom** [comment]
@Akshithsaai there's no need to update the color. Just fix the movie duration field. It should be in HH:MM:SS format.

**Comment by Akshithsaai** [comment]
@maniyaom I have Changed the Movie duration field to HH:MM:SS format. Should I validate the movie duration field also ?

for example : movie duration should not be greater 4 hours 

![image](https://github.com/user-attachments/assets/352cd3ff-ccd4-4c92-bd49-0637cd08aff2)

**Comment by Akshithsaai** [comment]
@maniyaom Could you kindly provide a response to my previous comment ?

**Comment by maniyaom** [comment]
@Akshithsaai please ensure that the user is not able to enter characters into this field.

**Comment by Akshithsaai** [comment]
@maniyaom I made sure that characters other numbers can't be entered into the field.

**Comment by maniyaom** [comment]
@Akshithsaai If everything is done please raise the PR and mention this issue number also.
for example: fixes: #<issue_number>
