### ISSUE TITLE
Browser Console Exposing Other User Details on Sign-In

### ISSUE THREAD

**Issue by MihirSaiDudekula** [maniyaom/Movie-Ticket-Booking#8]
**Summary:**  
The browser console is logging sensitive information about users who have signed in, including personal details and authentication data. This poses a security risk and violates user privacy.

**Steps to Reproduce:**  
1. Sign in with a user account.
2. Open the browser console (F12 or right-click > Inspect > Console).
3. Observe the logged details related to the signed-in user.

**Expected Behavior:**  
User details should not be logged in the console. Sensitive information should be kept private to protect user security and comply with best practices.

Reference Image:

**Labels:** gssoc24,hacktoberfest

---

**Comment by maniyaom** [comment]
@MihirSaiDudekula  ,please delete the shared screenshot first due to privacy concerns. You can proceed with working on the issue.

**Comment by MihirSaiDudekula** [comment]
Sorry, didn't realise that

> @MihirSaiDudekula ,please delete the shared screenshot first due to privacy concerns. You can proceed with working on the issue.

Sorry, didn't realise that
