### ISSUE TITLE
Login page not responsive 

### ISSUE THREAD

**Issue by Abhishek2634** [maniyaom/Movie-Ticket-Booking#82]
<img width="425" alt="Screenshot 2024-10-03 at 6 23 35 PM" src="https://github.com/user-attachments/assets/567f911e-c555-4760-8c92-8e77061c1b65">
<br/>
@maniyaom  I want to make it responsive. please assign me this issue. under gssoc, hacktoberfest tag. thanks.

**Comment by maniyaom** [comment]
@Abhishek2634 This issue is occurring because the navbar is not responsive. Someone is already working on making the navbar responsive. Please focus on other issues
