### ISSUE TITLE
Making Search movie feature

### ISSUE THREAD

**Issue by Rounit-1st** [maniyaom/Movie-Ticket-Booking#84]
Description:

I would like to request the addition of a Movie Search feature to the repository. This functionality will enable users to search for movies on the site, enhancing user experience and accessibility to the movie database.

Proposed Feature Details:

[ ] - Search Input: A search bar should be available on the homepage (or a designated search page), allowing users to input movie titles.
[ ] - Search Functionality: The search feature should query the movie database, returning relevant results based on the entered title. Results should include movie names, posters, release dates, and any other key information that enhances usability.
[ ]- Search by tag - Like Malayalam etc , which help user to search movies through relevant tags

Improved user experience by allowing efficient access to specific movies.
Easier navigation through the movie database, particularly for users with specific movie preferences.

Thank you for considering this feature request. I believe it will significantly improve the usability of the site.

**Comment by Rounit-1st** [comment]
sir can you assign level in this project

**Comment by maniyaom** [comment]
> sir can you assign level in this project
> 

Based on your PR I will give you a level. So fix this issue first.

**Comment by anuragbansalvips** [comment]
Hi @maniyaom  ,

I would like to work on this issue. Could you please assign it to me?

Thank you!

**Comment by anuragbansall** [comment]
Hi @maniyaom ,

I would like to work on this issue. Could you please assign it to me?

Thank you!

**Comment by maniyaom** [comment]
@anuragbansall assigned.
