### ISSUE TITLE
Responsiveness Issues on Smaller Screens

### ISSUE THREAD

**Issue by SurajSakhare100** [maniyaom/Movie-Ticket-Booking#89]
![Screenshot 2024-10-03 211551](https://github.com/user-attachments/assets/0315abf6-a172-43c7-a9d9-777d6d60f9c8)

Description:
When the application is viewed on screens smaller than 768px, the layout breaks, causing the navigation bar to overflow and the content to overlap. The page is not responsive to mobile and tablet views, significantly affecting user experience.

Expected Behavior:
The layout should adjust dynamically to different screen sizes, ensuring the app is usable on all devices.

Proposed Solution:
I can address these responsiveness issues by implementing CSS media queries to ensure that the layout adapts correctly to various screen sizes. I would utilize a mobile-first design approach to improve compatibility and user experience across devices.

Request for Assignment:
Please assign this issue to me, and I will work on implementing the necessary changes to enhance the application's responsiveness.

**Comment by itsmeAYUSH** [comment]
Could you please assign this issue to me under GSSOC'24 extd and Hacktoberfest?
I would like to work on this app to make it responsive and make it more user-friendly . Thanks!

**Comment by maniyaom** [comment]
@SurajSakhare100 This issue is due to the unresponsive navbar. Another contributor is working on it.

Issue: #43

**Comment by SurajSakhare100** [comment]
I'm not talking about making the navbar responsive, but I've made the entire homepage responsive with some UI updates. I'd also like to contribute to open-source, so please assign this task to me.

**Comment by maniyaom** [comment]
@SurajSakhare100 The home page was already responsive, but it became unresponsive due to the navbar.
