### ISSUE TITLE
images missing in about us section 

### ISSUE THREAD

**Issue by Karnmayank07** [maniyaom/Movie-Ticket-Booking#94]
img missing in about us page  like who we are ,  our mission  etc . and some text features and things need to be done 
![image](https://github.com/user-attachments/assets/94ab8380-d9b9-4219-8ca6-44113f0675fe)

assigned me this issue asap 🙂  i am ready with solution  

add label of hactoberfest , hactoberfest accepted  and gssoc extended too

**Comment by maniyaom** [comment]
@Karnmayank07 Image is already there.

![image](https://github.com/user-attachments/assets/a1bd2462-6393-46ba-b3a1-870a533f36c7)
