### ISSUE TITLE
footer is not available in login and signup page

### ISSUE THREAD

**Issue by shivamy009** [maniyaom/Movie-Ticket-Booking#96]
![Screenshot 2024-10-04 084647](https://github.com/user-attachments/assets/b901dc51-5589-40ac-8bca-c6a536d55bff)
footer is not availabe here

please assign me to fix it

**Comment by maniyaom** [comment]
@shivamy009 To justify adding the GSSoC-EXT label to your work, you'll need to incorporate additional features or functionality. Only then can I assign the label.

Let me know if you can add anything extra to it.
