### ISSUE TITLE
About section Improvement

### ISSUE THREAD

**Issue by NishantK-07** [maniyaom/Movie-Ticket-Booking#97]
The About section can be improved by making it look alike that of netflix about section page
![Uploading Screenshot 2024-10-04 100357.png…]()
![Uploading Screenshot 2024-10-04 100659.png…]()

**Comment by NishantK-07** [comment]
Please assign this issue to me under gssoc 2024 extended

**Comment by maniyaom** [comment]
@NishantK-07 It is not required right now.
