### ISSUE TITLE
Improve Code Structure and Performance Optimization in App.js

### ISSUE THREAD

**Issue by chikatlarakesh** [maniyaom/Movie-Ticket-Booking#98]
### **Title:**
Improve Code Structure and Performance Optimization in `App.js`

### **Description:**
The current implementation of the `App.js` file can be optimized for better performance, scalability, and maintainability. The following improvements are suggested:

1. **Component Separation:** Break down `App.js` into smaller, reusable components such as `MovieList`, `SeatSelection`, `BookingForm`, and `ConfirmationModal` to improve readability and organization.
   
2. **State Management:** Refactor state logic using hooks (`useState`, `useEffect`, `useReducer`), and ensure state is properly managed for loading, errors, and API responses.

3. **Loading and Error Handling:** Add proper loading indicators and user-friendly error messages when fetching data or handling booking processes.

4. **Performance Enhancements:**
   - Use memoization (`React.memo`, `useMemo`, `useCallback`) to prevent unnecessary re-renders.
   - Implement lazy loading (`React.lazy` and `Suspense`) for components to reduce initial load time.
   - Debounce search inputs to minimize excessive API calls.

5. **UI/UX Enhancements:**
   - Improve the seat selection interface with better color coding for seat availability.
   - Add a confirmation modal before finalizing the booking, showing the selected movie, time, and price.

Implementing these changes will enhance the performance and usability of the movie ticket booking app, providing a smoother experience for users.

**Comment by maniyaom** [comment]
@chikatlarakesh any update?
